version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    docker:
      - image: 'cimg/node:14.18.3'
    resource_class: small
    steps:
      - checkout
      - node/install:
        node-version: '14.17'
      - run: node --version
      - run: npm install
      - run: npm run test
  swagger:
    docker:
      - image: 'cimg/node:14.18.3'
    resource_class: small
    steps:
      - checkout
      - node/install:
        node-version: '14.17'
      - run: npm ci
      - run: npm run docs
      - run: cat swagger.json

workflows:
  pipeline: 
    jobs:
      - test:
          test-results-for: jest
      - swagger
          